import uuid
import tkinter as tk
from tkinter import messagebox, ttk
import pyperclip
import webbrowser

def generate_uuid():
    """Generate a new UUID and display it"""
    unique_id = uuid.uuid4()
    uuid_str = str(unique_id)
    uuid_hex = unique_id.hex
    
    # Update the text fields
    uuid_entry.delete(0, tk.END)
    uuid_entry.insert(0, uuid_str)
    
    hex_entry.delete(0, tk.END)
    hex_entry.insert(0, uuid_hex)
    
    status_label.config(text="🔥 New UUID generated by TECSO!", fg="#00ff87")

def copy_uuid():
    """Copy UUID to clipboard"""
    uuid_text = uuid_entry.get()
    if uuid_text:
        pyperclip.copy(uuid_text)
        status_label.config(text="📋 UUID copied to clipboard!", fg="#8b5cf6")
    else:
        messagebox.showwarning("Warning", "No UUID to copy!")

def copy_hex():
    """Copy UUID HEX to clipboard"""
    hex_text = hex_entry.get()
    if hex_text:
        pyperclip.copy(hex_text)
        status_label.config(text="📋 UUID HEX copied to clipboard!", fg="#8b5cf6")
    else:
        messagebox.showwarning("Warning", "No UUID HEX to copy!")

# Contact methods
def open_telegram():
    webbrowser.open("https://t.me/+989922068945")
    
def open_email():
    webbrowser.open("mailto:tecsoteam@gmail.com")
    
def open_website():
    webbrowser.open("https://tecso.team")

def open_github():
    webbrowser.open("https://github.com/Tecso-Dev")

# Create main window
root = tk.Tk()
root.title("🚀 TECSO UUID Generator")
root.geometry("600x500")
root.resizable(False, False)
root.configure(bg='#0d1117')

# Configure style
style = ttk.Style()
style.theme_use('clam')

# TECSO Colors
colors = {
    'bg_primary': '#0d1117',
    'bg_secondary': '#161b22', 
    'bg_tertiary': '#21262d',
    'accent_green': '#00ff87',
    'accent_purple': '#8b5cf6',
    'text_primary': '#f0f6fc',
    'text_secondary': '#8b949e'
}

# Configure custom styles
style.configure('Title.TLabel', 
               background=colors['bg_primary'],
               foreground=colors['accent_green'],
               font=('Segoe UI', 20, 'bold'))

style.configure('Subtitle.TLabel',
               background=colors['bg_primary'],
               foreground=colors['accent_purple'],
               font=('Segoe UI', 12, 'bold'))

style.configure('Info.TLabel',
               background=colors['bg_primary'],
               foreground=colors['text_secondary'],
               font=('Segoe UI', 9))

style.configure('TECSO.TFrame',
               background=colors['bg_secondary'],
               relief='solid',
               borderwidth=1)

style.configure('TECSO.TButton',
               background='#238636',
               foreground=colors['text_primary'],
               font=('Segoe UI', 10, 'bold'),
               relief='flat')

style.configure('Accent.TButton',
               background=colors['accent_purple'],
               foreground=colors['text_primary'],
               font=('Segoe UI', 12, 'bold'),
               relief='flat')

style.configure('Custom.TEntry',
               fieldbackground=colors['bg_tertiary'],
               foreground=colors['text_primary'],
               bordercolor='#30363d',
               insertcolor=colors['accent_green'])

# Main frame
main_frame = ttk.Frame(root, style='TECSO.TFrame', padding="30")
main_frame.pack(fill=tk.BOTH, expand=True, padx=20, pady=20)

# TECSO Header
header_frame = ttk.Frame(main_frame, style='TECSO.TFrame', padding="20")
header_frame.pack(fill=tk.X, pady=(0, 20))

title_label = ttk.Label(header_frame, text="🚀 TECSO", style='Title.TLabel')
title_label.pack()

subtitle_label = ttk.Label(header_frame, text="UUID Generator", style='Subtitle.TLabel')
subtitle_label.pack(pady=(0, 10))

tagline_label = ttk.Label(header_frame, text="Professional UUID Generation Tool", style='Info.TLabel')
tagline_label.pack()

# Contact section
contact_frame = ttk.Frame(main_frame, style='TECSO.TFrame', padding="15")
contact_frame.pack(fill=tk.X, pady=(0, 20))

contact_label = ttk.Label(contact_frame, text="🔗 Quick Contact", style='Subtitle.TLabel')
contact_label.pack(pady=(0, 10))

contact_buttons = ttk.Frame(contact_frame, style='TECSO.TFrame')
contact_buttons.pack()

ttk.Button(contact_buttons, text="📱 Telegram", command=open_telegram, style='TECSO.TButton', width=12).pack(side=tk.LEFT, padx=5)
ttk.Button(contact_buttons, text="📧 Email", command=open_email, style='TECSO.TButton', width=12).pack(side=tk.LEFT, padx=5)
ttk.Button(contact_buttons, text="🌐 Website", command=open_website, style='TECSO.TButton', width=12).pack(side=tk.LEFT, padx=5)
ttk.Button(contact_buttons, text="💻 GitHub", command=open_github, style='TECSO.TButton', width=12).pack(side=tk.LEFT, padx=5)

# UUID Generation Section
uuid_frame = ttk.Frame(main_frame, style='TECSO.TFrame', padding="20")
uuid_frame.pack(fill=tk.X, pady=(0, 20))

# UUID Section
uuid_label = ttk.Label(uuid_frame, text="🆔 UUID:", style='Subtitle.TLabel')
uuid_label.grid(row=0, column=0, sticky=tk.W, pady=10)

uuid_entry = ttk.Entry(uuid_frame, width=45, font=("Consolas", 11), style='Custom.TEntry')
uuid_entry.grid(row=0, column=1, padx=15, pady=10)

copy_uuid_btn = ttk.Button(uuid_frame, text="📋 Copy", command=copy_uuid, style='TECSO.TButton')
copy_uuid_btn.grid(row=0, column=2, pady=10)

# UUID HEX Section
hex_label = ttk.Label(uuid_frame, text="🔑 UUID HEX:", style='Subtitle.TLabel')
hex_label.grid(row=1, column=0, sticky=tk.W, pady=10)

hex_entry = ttk.Entry(uuid_frame, width=45, font=("Consolas", 11), style='Custom.TEntry')
hex_entry.grid(row=1, column=1, padx=15, pady=10)

copy_hex_btn = ttk.Button(uuid_frame, text="📋 Copy", command=copy_hex, style='TECSO.TButton')
copy_hex_btn.grid(row=1, column=2, pady=10)

# Generate button
generate_btn = ttk.Button(uuid_frame, text="⚡ Generate New UUID", 
                         command=generate_uuid, style='Accent.TButton')
generate_btn.grid(row=2, column=0, columnspan=3, pady=20)

# Status label
status_label = tk.Label(main_frame, text="✅ Ready to generate TECSO UUID", 
                       font=("Segoe UI", 10), fg=colors['accent_green'], bg=colors['bg_secondary'])
status_label.pack(pady=15)

# Instructions
instructions = """🔧 Instructions:
1. Click 'Generate New UUID' to create a unique identifier
2. Copy the UUID or UUID HEX as needed for your mobile profile
3. Use this unique ID in your iPhone configuration profile"""

instructions_label = tk.Label(main_frame, text=instructions, 
                             font=("Segoe UI", 9), fg=colors['text_secondary'], 
                             bg=colors['bg_secondary'], justify=tk.LEFT)
instructions_label.pack(pady=15)

# Footer
footer_label = tk.Label(main_frame, text="© 2025 TECSO Team - Professional Mobile Solutions", 
                       font=("Segoe UI", 8), fg=colors['text_secondary'], bg=colors['bg_secondary'])
footer_label.pack(side=tk.BOTTOM, pady=10)

# Generate initial UUID
generate_uuid()

# Configure grid weights
uuid_frame.columnconfigure(1, weight=1)

# Start the GUI
if __name__ == "__main__":
    root.mainloop()
